In [11]:
import numpy as np
from scipy.linalg import inv

In [19]:
norm_factors = np.array([2, 5])

N_x_inv = np.diagflat(norm_factors) 

N_x = inv(N_x_inv)

print(f"N_x_inv: \n{N_x_inv}")
print(f"N_x: \n{N_x}")

A = np.array([[2, 4],[1, 3]])

N_x_inv: 
[[2 0]
 [0 5]]
N_x: 
[[ 0.5 -0. ]
 [ 0.   0.2]]


In [8]:
%run -i laguerre_delay.py
#print(LaguerreDelay(theta = 256, order = 19).A.shape)
print(LaguerreDelay(theta = 256, order = 19).B.shape)
#print(LaguerreDelay(theta = 256, order = 19).C.shape)
#print(LaguerreDelay(theta = 256, order = 19).D.shape)

(19, 1)


array([[0.]])

In [35]:
approx = LegendreDelay(theta = 0.5, order = 4)

In [30]:
realizer = Identity()
realizer_result = realizer(LegendreDelay(theta = 0.5, order = 4))

In [33]:
realizer_result

RealizerResult(sys=LinearSystem(sys=(array([[ -2.,  -2.,  -2.,  -2.],
       [  6.,  -6.,  -6.,  -6.],
       [-10.,  10., -10., -10.],
       [ 14., -14.,  14., -14.]]), array([[  2.],
       [ -6.],
       [ 10.],
       [-14.]]), array([[1., 1., 1., 1.]]), array([0.])), analog=True), T=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), Tinv=array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]]), realization=LinearSystem(sys=(array([[ -2.,  -2.,  -2.,  -2.],
       [  6.,  -6.,  -6.,  -6.],
       [-10.,  10., -10., -10.],
       [ 14., -14.,  14., -14.]]), array([[  2.],
       [ -6.],
       [ 10.],
       [-14.]]), array([[1., 1., 1., 1.]]), array([[0.]])), analog=True))

In [24]:
import numpy as np
#import control as ctrl

def _check_order(order):
    if order < 1 or not is_integer(order):
        raise ValueError("order (%s) must be integer >= 1" % order)
    return order

def is_integer(obj):
    int_types = (int,)
    return isinstance(obj, int_types + (np.integer,))

theta = 0.5
order = 3

q = _check_order(order)

# This is the independent variable.
Q = np.arange(q, dtype=np.float64)
print(f"Q = {Q}\n")

R = (2*Q + 1)[:, None] / theta
print(f"R = {R}\n")

j, i = np.meshgrid(Q, Q)
print(f"j = {j} (column index)\n")
print(f"i = {i} (row index)\n")

A = np.where(i < j, -1, (-1.)**(i-j+1)) * R
print(f"A = {A}")

B = (-1.)**Q[:, None] * R
print(f"B = {B}")

C = np.ones((1, q))
print(f"C = {C}")

D = np.zeros((1,))
print(f"D = {D}")

Q = [0. 1. 2.]

R = [[ 2.]
 [ 6.]
 [10.]]

j = [[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]] (column index)

i = [[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]] (row index)

A = [[ -2.  -2.  -2.]
 [  6.  -6.  -6.]
 [-10.  10. -10.]]
B = [[ 2.]
 [-6.]
 [10.]]
C = [[1. 1. 1.]]
D = [0.]
